plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

def localProps = new Properties()
file("local.properties").withInputStream { localProps.load(it) }

def opencvJarPath = localProps['opencv.jar.path']
if(opencvJarPath == null) {
    throw new GradleException("Missing opencv.jar.path in local.properties")
}

dependencies {
    implementation 'org.json:json:20240303'
    implementation files(opencvJarPath)
    implementation "org.controlsfx:controlsfx:11.2.0"
}

application {
    mainClass = 'org.example.Main'
}
